export const $search = () => document.getElementById('search');
export const $fundHouse = () => document.getElementById('fundHouse');
export const $category = () => document.getElementById('category');
export const $invtype = () => document.getElementById('invtype');
export const $categorynameList = () => document.getElementById('categorynameList');
export const $apply = () => document.getElementById('apply');
export const $reset = () => document.getElementById('reset');
export const $resultsBody = () => document.querySelector('#results tbody');
export const $resultCount = () => document.getElementById('resultCount');
export const $pageSize = () => document.getElementById('pageSize');
export const $prev = () => document.getElementById('prev');
export const $next = () => document.getElementById('next');
export const $curPage = () => document.getElementById('curPage');
export const $totalPages = () => document.getElementById('totalPages');
export const $noResults = () => document.getElementById('noResults');
